#!/usr/bin/env node
/**
 * build-brand.mjs — regenerate every brand asset from the one master image.
 *
 * The master is `brand/starspace-mark.png`: the carved-wood *Space star, the
 * mark the community has always used. Everything visual that carries the brand
 * is derived from it here, so there is exactly one file to change when the mark
 * changes, and no hand-drawn approximation of it can drift back in.
 *
 * Outputs (all into `static/`, all committed):
 *   brand/starspace-mark.webp   in-page mark for the nav and footer
 *   favicon.svg                 default tab icon (the night tile)
 *   favicon-dark.svg            tab icon for a dark UI
 *   favicon-light.svg           tab icon for a light UI
 *   apple-touch-icon.png        180x180, RGB — Apple rejects an alpha channel
 *   icon-192.png / icon-512.png PWA install icons, RGB
 *   og-image.png                1200x630 share card, from brand/og-image.svg
 *
 * Run it after changing the master or the share-card source:
 *   bun run build:brand
 *
 * Not part of `bun run build`. It needs ImageMagick 7 (`magick`) and
 * `rsvg-convert`, its output is committed, and it should run only when the
 * artwork or the card's wording actually changes.
 */
import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const brand = (...p) => join(ROOT, 'brand', ...p);
const out = (...p) => join(ROOT, 'static', ...p);

const MASTER = brand('starspace-mark.png');
/** Tile ground. Also `theme_color` in the manifest and `<meta name="theme-color">`. */
const NIGHT = '#0b1026';

const run = (cmd, args) => execFileSync(cmd, args, { stdio: ['ignore', 'pipe', 'inherit'] });

function requireTool(cmd, args, hint) {
	try {
		execFileSync(cmd, args, { stdio: 'ignore' });
	} catch {
		console.error(`\n✗ ${cmd} is required. ${hint}\n`);
		process.exit(1);
	}
}

requireTool('magick', ['-version'], 'Install ImageMagick 7.');
requireTool('rsvg-convert', ['--version'], 'Install librsvg.');

/** The master, scaled to `size` and inlined as a data URI for the SVG tiles.
 *  Embedded rather than referenced: browsers routinely refuse to load external
 *  resources from an SVG used as a favicon, and a broken reference there fails
 *  silently as a blank tab icon. */
function markDataUri(size) {
	const tmp = join(ROOT, '.llm-outputs', `mark-${size}.png`);
	mkdirSync(join(ROOT, '.llm-outputs'), { recursive: true });
	run('magick', [MASTER, '-resize', `${size}x${size}`, '-strip', tmp]);
	return `data:image/png;base64,${readFileSync(tmp).toString('base64')}`;
}

// ── Tab favicons ────────────────────────────────────────────────────────────
// One geometry, two grounds. The mark is bronze, which holds against both, so
// only the tile behind it changes between the light and dark variants.
const MARK_128 = markDataUri(128);

const tile = (
	comment,
	defs,
	ground,
	extras = ''
) => `<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 512 512" role="img" aria-label="*Space">
	<title>*Space</title>
	<!--
		GENERATED by scripts/build-brand.mjs from brand/starspace-mark.png.
		Do not hand-edit; change the master or the script and re-run
		\`bun run build:brand\`.

		${comment}
	-->
	<defs>
${defs}
	</defs>
	<rect width="512" height="512" rx="104" fill="${ground}" />
${extras}	<image x="66" y="66" width="380" height="380" preserveAspectRatio="xMidYMid meet" href="${MARK_128}" />
</svg>
`;

const darkTile = tile(
	'The night tile. Bronze on navy is also what the app icons and the share card use.',
	`		<radialGradient id="tile" cx="48%" cy="40%" r="72%">
			<stop offset="0" stop-color="#1b2450" />
			<stop offset="1" stop-color="#070c1f" />
		</radialGradient>`,
	'url(#tile)'
);

const lightTile = tile(
	'The light tile, for a light browser chrome. A coral hairline keeps the ' +
		'rounded square visible against a white tab strip.',
	`		<linearGradient id="tile" x1="0" y1="0" x2="1" y2="1">
			<stop offset="0" stop-color="#ffffff" />
			<stop offset="1" stop-color="#fff1ec" />
		</linearGradient>`,
	'url(#tile)',
	'	<rect x="16" y="16" width="480" height="480" rx="90" fill="none" stroke="#ffd5cc" stroke-width="12" />\n'
);

writeFileSync(out('favicon-dark.svg'), darkTile);
writeFileSync(out('favicon-light.svg'), lightTile);
// The default is the night tile: a browser that ignores the prefers-color-scheme
// pair gets an icon that reads on a light chrome as well as a dark one, where a
// white tile would vanish into a light tab strip.
writeFileSync(
	out('favicon.svg'),
	darkTile.replace(
		'The night tile.',
		'Default tab icon, used by anything that ignores the prefers-color-scheme pair. The night tile.'
	)
);
console.log('✓ favicon.svg, favicon-dark.svg, favicon-light.svg');

// ── Installed-app icons ─────────────────────────────────────────────────────
// Flattened to RGB on purpose: Apple rejects an alpha channel in a touch icon,
// and tests/unit/product-identity.test.ts checks the PNG colour type.
for (const [file, size] of [
	['apple-touch-icon.png', 180],
	['icon-192.png', 192],
	['icon-512.png', 512]
]) {
	run('magick', [
		'-size',
		`${size}x${size}`,
		`radial-gradient:#1b2450-#070c1f`,
		'(',
		MASTER,
		'-resize',
		`${Math.round(size * 0.74)}x${Math.round(size * 0.74)}`,
		')',
		'-gravity',
		'center',
		'-composite',
		'-background',
		NIGHT,
		'-alpha',
		'remove',
		'-alpha',
		'off',
		// Quantised: the mark is a photograph of wood, so a 256-colour palette is
		// visually identical and takes a 512px install icon from 570K to ~120K.
		'-colors',
		'256',
		'-strip',
		'-define',
		'png:color-type=2',
		out(file)
	]);
	console.log(`✓ ${file} (${size}x${size})`);
}

// ── In-page mark ────────────────────────────────────────────────────────────
// Transparent, so the nav and footer show it on whatever the theme paints.
run('magick', [
	MASTER,
	'-resize',
	'256x256',
	'-quality',
	'86',
	'-strip',
	out('brand', 'starspace-mark.webp')
]);
console.log('✓ brand/starspace-mark.webp');

// ── Share card ──────────────────────────────────────────────────────────────
// brand/og-image.svg is the layout; the mark is injected here so the source
// stays readable and the two cannot disagree about which star is current.
// replaceAll, not replace: the source's own comment names the placeholder, and
// that mention comes first in the file. Substituting only the first match put
// the mark's data URI inside the comment and shipped a card with no star on it.
const card = readFileSync(brand('og-image.svg'), 'utf8').replaceAll('{{MARK}}', markDataUri(420));
const cardTmp = join(ROOT, '.llm-outputs', 'og-image.svg');
writeFileSync(cardTmp, card);
run('rsvg-convert', ['-w', '1200', '-h', '630', cardTmp, '-o', out('og-image.png')]);
run('magick', [
	out('og-image.png'),
	'-background',
	NIGHT,
	'-alpha',
	'remove',
	'-alpha',
	'off',
	'-strip',
	'-define',
	'png:color-type=2',
	out('og-image.png')
]);
console.log('✓ og-image.png (1200x630)');

// ── The embeddable badge's mark ─────────────────────────────────────────────
// The "Built at *Space" badge is meant to be pasted onto sites we do not own,
// and into READMEs, where it renders as an <img> from /badge.svg. An SVG used
// as an image may not fetch anything external — the same rule that makes the
// favicons inline their mark — so the badge has to carry the artwork inside it.
//
// 40px is what a 20px badge mark needs on a 2x screen. It lands in a generated
// module rather than a JSON asset so the badge builder can import it directly
// and the bundler can tree-shake around it.
const badgeMark = markDataUri(40);
const generatedDir = join(ROOT, 'src', 'lib', 'generated');
mkdirSync(generatedDir, { recursive: true });
writeFileSync(
	join(generatedDir, 'badge-mark.ts'),
	`// GENERATED by scripts/build-brand.mjs — do not edit.\n` +
		`// The *Space mark at 40px, inlined so the badge is self-contained wherever it\n` +
		`// is pasted. Regenerate with \`bun run build:brand\`.\n` +
		`export const BADGE_MARK_DATA_URI =\n\t'${badgeMark}';\n`
);
console.log('✓ src/lib/generated/badge-mark.ts (40px mark, inlined)');

// The same 40px mark as a served file. The HTML, React, Svelte and Vue snippets
// use a URL rather than a data URI — pasting 5KB of base64 into someone's JSX is
// hostile — so the badge needs a real, stable image endpoint too.
run('magick', [MASTER, '-resize', '40x40', '-strip', out('badge-mark.png')]);
console.log('✓ badge-mark.png (40x40)');

console.log('\nBrand assets rebuilt from brand/starspace-mark.png.');
